-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

CREATE TABLE [ActivationInfo]
 (
	[RegisteredUser]			Text (50) NOT NULL, 
	[ActivationCode]			Text (6) NOT NULL, 
	[MUID]			Text (23), 
	[MHFP]			Memo/Hyperlink (255)
);

CREATE TABLE [Booth]
 (
	[ID]			Text (8), 
	[StoreNumber]			Long Integer, 
	[DealerID]			Text (8), 
	[Description]			Text (100), 
	[TotalAreaSqFt]			Double, 
	[PricePerSqFt]			Currency, 
	[CalculatedRent]			Currency, 
	[UseCalculatedRent]			Boolean NOT NULL, 
	[Rent]			Currency, 
	[Notes]			Memo/Hyperlink (255), 
	[Tips]			Memo/Hyperlink (255), 
	[BoothIDValue]			Text (24), 
	[UseConsignmentPct]			Boolean NOT NULL, 
	[ConsignmentPct]			Double, 
	[UseDiscountPct]			Boolean NOT NULL, 
	[DiscountPct]			Double, 
	[UseDiscountSchedule]			Boolean NOT NULL, 
	[DiscountSchedule]			Text (50), 
	[DiscountStartDate]			DateTime, 
	[DiscountEndDate]			DateTime, 
	[Polygon]			Text (240)
);

CREATE TABLE [Cashier]
 (
	[Cashier]			Text (20), 
	[Password]			Text (40), 
	[Admin]			Boolean NOT NULL, 
	[FirstName]			Text (50), 
	[LastName]			Text (50), 
	[Address1]			Text (50), 
	[Address2]			Text (50), 
	[City]			Text (50), 
	[State]			Text (20), 
	[ZIP]			Text (10), 
	[PrimaryPhone]			Text (20), 
	[AltPhone]			Text (20), 
	[MobilePhone]			Text (20), 
	[Email]			Text (80), 
	[ItemAdmin]			Boolean NOT NULL, 
	[CommissionPct]			Double, 
	[BoothID]			Text (100), 
	[CashierAdmin]			Boolean NOT NULL, 
	[PrimaryRole]			Text (50), 
	[CorrectionsAdmin]			Boolean NOT NULL, 
	[DiscountingAllowed]			Boolean NOT NULL, 
	[AllowRentPayments]			Boolean NOT NULL, 
	[AcceptExpiredGiftCertificates]			Boolean NOT NULL, 
	[AllowVoidApproval]			Boolean NOT NULL, 
	[DealerAdmin]			Boolean NOT NULL, 
	[AllowNewLayaways]			Boolean NOT NULL, 
	[AllowLayawayPayments]			Boolean NOT NULL, 
	[AllowSellGCs]			Boolean NOT NULL, 
	[DealerModuleAccess]			Boolean NOT NULL, 
	[DealerModuleLogonRequired]			Boolean NOT NULL, 
	[DealerInfoAccess]			Boolean NOT NULL, 
	[DealerInfoLogonRequired]			Boolean NOT NULL, 
	[ReportModuleAccess]			Boolean NOT NULL, 
	[ReportModuleLogonRequired]			Boolean NOT NULL, 
	[CustomerReportAccess]			Boolean NOT NULL, 
	[DealerReportAccess]			Boolean NOT NULL, 
	[InventoryReportAccess]			Boolean NOT NULL, 
	[LabelReportAccess]			Boolean NOT NULL, 
	[ResellerReportAccess]			Boolean NOT NULL, 
	[SalespersonReportAccess]			Boolean NOT NULL, 
	[StoreReportAccess]			Boolean NOT NULL, 
	[TaxReportAccess]			Boolean NOT NULL, 
	[SettingsGroupAccess]			Boolean NOT NULL, 
	[SettlementModuleAccess]			Boolean NOT NULL, 
	[AllowSetDealerGatewayAdmin]			Boolean NOT NULL, 
	[AllowRefundAsNewGiftCertificate]			Boolean NOT NULL, 
	[DealerID]			Text (8), 
	[AllowInstallUpdates]			Boolean NOT NULL, 
	[CanAddCashiers]			Boolean NOT NULL, 
	[AllowSetDealerGatewayAdminLogonRequired]			Boolean NOT NULL, 
	[CanDeleteCashiers]			Boolean NOT NULL, 
	[ItemMasterCanAdd]			Boolean NOT NULL, 
	[ItemMasterCanDelete]			Boolean NOT NULL, 
	[ItemMasterCanDeleteLogonRequired]			Boolean NOT NULL, 
	[ItemMasterCanEdit]			Boolean NOT NULL, 
	[ItemMasterCanEditID]			Boolean NOT NULL, 
	[AllowGCListAccess]			Boolean NOT NULL, 
	[Notes]			Memo/Hyperlink (255), 
	[AllowNoSale]			Boolean NOT NULL, 
	[ResellerModuleAccess]			Boolean NOT NULL, 
	[ResellerCanManage]			Boolean NOT NULL, 
	[Active]			Boolean NOT NULL, 
	[Country]			Text (50), 
	[GCAdmin]			Boolean NOT NULL, 
	[CanDeleteCashEntries]			Boolean NOT NULL, 
	[CanAddDealer]			Boolean NOT NULL, 
	[CanDeleteDealer]			Boolean NOT NULL, 
	[CanEditDealerBasicInfo]			Boolean NOT NULL, 
	[CanEditDealerInternetInfo]			Boolean NOT NULL, 
	[CanEditDealerCustomerRestrictions]			Boolean NOT NULL, 
	[CanEditDealerRates]			Boolean NOT NULL, 
	[CanEditDealerCommission]			Boolean NOT NULL, 
	[CanEditDealerDiscount]			Boolean NOT NULL, 
	[CanEditDealerContactInfo]			Boolean NOT NULL, 
	[CanEditDealerBusinessInfo]			Boolean NOT NULL, 
	[CanEditDealerAltInfo]			Boolean NOT NULL, 
	[CanEditDealerSettlementInfo]			Boolean NOT NULL, 
	[CanEditDealerWorkCreditInfo]			Boolean NOT NULL, 
	[CanEditDealerExtraInfo]			Boolean NOT NULL, 
	[CanEditDealerFee]			Boolean NOT NULL, 
	[CanEditDealerRent]			Boolean NOT NULL, 
	[OrderModuleAccess]			Boolean NOT NULL, 
	[CanManageOrders]			Boolean NOT NULL, 
	[CanPopCashDrawerManually]			Boolean NOT NULL, 
	[BoothModuleAccess]			Boolean NOT NULL, 
	[BoothModuleLogonRequired]			Boolean NOT NULL, 
	[CanAddBooth]			Boolean NOT NULL, 
	[CanDeleteBooth]			Boolean NOT NULL, 
	[CanEditBoothInfo]			Boolean NOT NULL
);

CREATE TABLE [Company]
 (
	[Name]			Text (50), 
	[Addr1]			Text (50), 
	[Addr2]			Text (50), 
	[City]			Text (50), 
	[State]			Text (20), 
	[ZIP]			Text (10), 
	[Phone]			Text (14), 
	[MultiStore]			Boolean NOT NULL, 
	[ReportLogo]			OLE (255), 
	[Email]			Text (100), 
	[Website]			Text (100), 
	[PrintName]			Boolean NOT NULL, 
	[PrintAddr1]			Boolean NOT NULL, 
	[PrintAddr2]			Boolean NOT NULL, 
	[PrintCityStateZIP]			Boolean NOT NULL, 
	[PrintPhone]			Boolean NOT NULL, 
	[PrintEmail]			Boolean NOT NULL, 
	[PrintWebsite]			Boolean NOT NULL, 
	[FederalTaxIDNo]			Text (11), 
	[Country]			Text (50)
);

CREATE TABLE [Customer]
 (
	[ID]			Double, 
	[FirstName]			Text (50), 
	[LastName]			Text (50), 
	[Address1]			Text (50), 
	[Address2]			Text (50), 
	[City]			Text (50), 
	[State]			Text (20), 
	[ZIP]			Text (10), 
	[PrimaryPhone]			Text (20), 
	[AltPhone]			Text (20), 
	[MobilePhone]			Text (20), 
	[Email]			Text (80), 
	[Comments]			Memo/Hyperlink (255), 
	[Notes]			Memo/Hyperlink (255), 
	[Password]			Text (20), 
	[MarketingOK]			Boolean NOT NULL, 
	[PersonType]			Text (50), 
	[CostPriceType]			Text (20), 
	[DiscountPct]			Double, 
	[Taxed]			Boolean NOT NULL, 
	[NoSale]			Boolean NOT NULL, 
	[InventoryAction]			Text (20), 
	[Company]			Text (50), 
	[Extra1]			Text (50), 
	[Extra2]			Text (50), 
	[Extra3]			Text (50), 
	[Extra4]			Text (50), 
	[Extra5]			Text (50), 
	[URL]			Text (255), 
	[MobileEmail]			Text (100), 
	[LoyaltyID]			Text (16), 
	[LoyaltyPlan]			Text (50), 
	[AllowLayaways]			Boolean NOT NULL, 
	[AllowChecks]			Boolean NOT NULL, 
	[DLN]			Text (20), 
	[RequireCashOnly]			Boolean NOT NULL, 
	[ShippingUseContact]			Boolean NOT NULL, 
	[ShippingFirstName]			Text (50), 
	[ShippingLastName]			Text (50), 
	[ShippingAddress1]			Text (50), 
	[ShippingAddress2]			Text (50), 
	[ShippingCity]			Text (50), 
	[ShippingState]			Text (20), 
	[ShippingZIP]			Text (10), 
	[ShippingPhone]			Text (20), 
	[Country]			Text (50), 
	[ShippingCountry]			Text (50), 
	[EditDate]			DateTime, 
	[UploadDate]			DateTime, 
	[DOB]			DateTime
);

CREATE TABLE [Dealer]
 (
	[ID]			Text (8), 
	[DealerIDValue]			Text (24), 
	[EditTimeStamp]			DateTime, 
	[Active]			Boolean NOT NULL, 
	[UseActiveDate]			Boolean NOT NULL, 
	[ActiveDate]			DateTime, 
	[ActiveEndDate]			DateTime, 
	[FirstName]			Text (50), 
	[LastName]			Text (50), 
	[Address1]			Text (50), 
	[Address2]			Text (50), 
	[City]			Text (50), 
	[State]			Text (20), 
	[ZIP]			Text (10), 
	[PrimaryPhone]			Text (20), 
	[AltPhone]			Text (20), 
	[MobilePhone]			Text (20), 
	[PreferredFormOfContact]			Text (25), 
	[Admin]			Boolean NOT NULL, 
	[Registered]			Boolean NOT NULL, 
	[Password]			Text (40), 
	[PasswordTimeStamp]			DateTime, 
	[MobileAlert]			Boolean NOT NULL, 
	[Email]			Text (80), 
	[MobileEmail]			Text (100), 
	[MobileEmailTimeStamp]			DateTime, 
	[DealerPct]			Double, 
	[ConsignmentPct]			Double, 
	[CommissionSchedule]			Text (50), 
	[UseDiscountPct]			Boolean NOT NULL, 
	[DiscountPct]			Double, 
	[UseDiscountSchedule]			Boolean NOT NULL, 
	[DiscountSchedule]			Text (50), 
	[DiscountStartDate]			DateTime, 
	[DiscountEndDate]			DateTime, 
	[HasPhoneNotes]			Boolean NOT NULL, 
	[PhoneNotes]			Memo/Hyperlink (255), 
	[HasNotes]			Boolean NOT NULL, 
	[Notes]			Memo/Hyperlink (255), 
	[HasTips]			Boolean NOT NULL, 
	[Tips]			Memo/Hyperlink (255), 
	[AllowCreditCards]			Boolean NOT NULL, 
	[AllowLayaways]			Boolean NOT NULL, 
	[RegistrationKey]			Text (6), 
	[PaysRent]			Boolean NOT NULL, 
	[Rent]			Currency, 
	[UseCalculatedRent]			Boolean NOT NULL, 
	[PaysTransactionalFees]			Boolean NOT NULL, 
	[PaysSalesTax]			Boolean NOT NULL, 
	[FlatFeeRate]			Double, 
	[FeeMethod]			Long Integer, 
	[PrintBusinessName]			Boolean NOT NULL, 
	[Company]			Text (50), 
	[ResellerNo]			Text (25), 
	[BusinessLicenseNo]			Text (25), 
	[AltAddress1]			Text (50), 
	[AltAddress2]			Text (50), 
	[AltAddress3]			Text (50), 
	[AltCity]			Text (50), 
	[AltState]			Text (20), 
	[AltZIP]			Text (10), 
	[AltEmail]			Text (80), 
	[AltWebsite2]			Text (100), 
	[AltWebsite3]			Text (100), 
	[AltWebsite4]			Text (100), 
	[AltWebsite5]			Text (100), 
	[Extra1]			Text (50), 
	[Extra2]			Text (50), 
	[Extra3]			Text (50), 
	[Extra4]			Text (50), 
	[Extra5]			Text (50), 
	[URL]			Text (255), 
	[Website]			Text (100), 
	[CarrySettlementBalanceForward]			Boolean NOT NULL, 
	[GetsHardCopyDDR]			Boolean NOT NULL, 
	[GetsHardCopyDFSR]			Boolean NOT NULL, 
	[GetsPDFCopyDDR]			Boolean NOT NULL, 
	[GetsPDFCopyDFSR]			Boolean NOT NULL, 
	[FederalTaxIDNo]			Text (11), 
	[StateTaxIDNo]			Text (20), 
	[UseWorkCreditLumpSum]			Boolean NOT NULL, 
	[WorkCreditLumpSumAmount]			Currency, 
	[WorkCreditLumpSumMinHours]			Double, 
	[UseWorkCreditHourlyRate]			Boolean NOT NULL, 
	[PayRate]			Currency, 
	[UseWorkCreditHourlyMaxAmount]			Boolean NOT NULL, 
	[WorkCreditHourlyMaxAmount]			Currency, 
	[Country]			Text (50), 
	[AltCountry]			Text (50), 
	[AllowItemUpload]			Boolean NOT NULL, 
	[AllowBuyOnAccount]			Boolean NOT NULL, 
	[AllowSellOnAccount]			Boolean NOT NULL, 
	[AllowDMI]			Boolean NOT NULL, 
	[DefaultPaymentType]			Text (10), 
	[DOB]			DateTime, 
	[DealerGroup]			Text (25), 
	[ShopWideDiscountOptOut]			Boolean NOT NULL, 
	[UseIECS]			Boolean NOT NULL, 
	[IECS]			Text (50), 
	[IECS1]			Text (255), 
	[IECS2]			Text (255), 
	[IECS3]			Text (255), 
	[IECS4]			Text (255), 
	[IECS5]			Text (255), 
	[UseICCSProfileID]			Boolean NOT NULL, 
	[ICCSProfileID]			Text (50)
);

CREATE TABLE [DealerFee]
 (
	[ID]			Long Integer, 
	[DealerID]			Text (8), 
	[Type]			Text (50), 
	[Description]			Text (80), 
	[Amount]			Currency, 
	[FlatFeeRate]			Double, 
	[StartDate]			DateTime, 
	[EndDate]			DateTime
);

CREATE TABLE [DeletedOrders]
 (
	[ID]			Double, 
	[TimeDateStamp]			DateTime, 
	[Cashier]			Text (20)
);

CREATE TABLE [DeletedTransactions]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[TimeDateStamp]			DateTime, 
	[SalesMasterID]			Double, 
	[Cashier]			Text (20), 
	[RefundMethod]			Text (255), 
	[ApprovingCashier]			Text (20), 
	[Customer]			Text (50), 
	[CashAmount]			Currency, 
	[CheckAmount]			Currency, 
	[CreditAmount]			Currency, 
	[DebitAmount]			Currency, 
	[GiftCertificateAmount]			Currency, 
	[NoSaleAmount]			Currency, 
	[StoreCheckAmount]			Currency, 
	[CashOtherAmount]			Currency, 
	[OtherAmount]			Currency, 
	[AccountAmount]			Currency, 
	[ChargeAmount]			Currency, 
	[GiftCardAmount]			Currency
);

CREATE TABLE [Fee]
 (
	[ListPosition]			Long Integer, 
	[Type]			Text (20), 
	[Description]			Text (80), 
	[Amount]			Currency, 
	[StartDate]			DateTime, 
	[EndDate]			DateTime, 
	[ID]			Double, 
	[FeeValue]			Text (20)
);

CREATE TABLE [FloorplanDetail]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[ObjectType]			Text (20), 
	[BoothID]			Text (8), 
	[DealerID]			Text (8), 
	[Description]			Text (255), 
	[Polygon]			Text (240), 
	[Rotate]			Double, 
	[TotalAreaSqft]			Double, 
	[PricePerSqFt]			Currency, 
	[Rent]			Currency, 
	[SalesTotal]			Currency, 
	[ItemCount]			Double, 
	[StartDate]			DateTime, 
	[EndDate]			DateTime
);

CREATE TABLE [FloorplanMaster]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[Status]			Text (20), 
	[Description]			Text (255), 
	[AddedBy]			Text (20), 
	[AddedDate]			DateTime, 
	[EditedBy]			Text (20), 
	[EditDate]			DateTime
);

CREATE TABLE [GiftCertificate]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[SalesMasterID]			Double, 
	[CustomerID]			Double, 
	[Amount]			Currency, 
	[RecipientName]			Text (80), 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[Description]			Text (80), 
	[BodyText]			Memo/Hyperlink (255), 
	[BackgroundImage]			Text (255), 
	[ExpirationDate]			DateTime, 
	[AlternateGCTrackingNumber]			Text (80)
);

CREATE TABLE [GiftCertificateAdjustment]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[TimeDateStamp]			DateTime, 
	[Cashier]			Text (20), 
	[Amount]			Currency, 
	[Description]			Text (80), 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer
);

CREATE TABLE [Item]
 (
	[ID]			Text (16), 
	[ParentID]			Text (16), 
	[DealerID]			Text (8), 
	[Description]			Text (255), 
	[Price]			Currency, 
	[Cost]			Currency, 
	[Movement]			Double, 
	[UOM]			Text (20), 
	[Size]			Text (20), 
	[Quantity]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[Manufacturer]			Text (50), 
	[Brand]			Text (50), 
	[Distributor]			Text (50), 
	[ReorderRule]			Text (255), 
	[ReorderQuantity]			Double, 
	[ConsignFlag]			Boolean NOT NULL, 
	[ConsignmentPct]			Double, 
	[ConsignmentRule]			Text (255), 
	[ConsignmentStartDate]			DateTime, 
	[ConsignmentEndDate]			DateTime, 
	[DiscountPct]			Double, 
	[DiscountStartDate]			DateTime, 
	[DiscountEndDate]			DateTime, 
	[AddedDate]			DateTime, 
	[EditDate]			DateTime, 
	[Status]			Text (50), 
	[Notes]			Memo/Hyperlink (255), 
	[SellerID]			Long Integer, 
	[Taxable]			Boolean NOT NULL, 
	[TaxCategory]			Text (100), 
	[Department]			Text (100), 
	[Category]			Text (100), 
	[Supplier]			Text (100), 
	[BarCodeType]			Text (20), 
	[SpecialItemFlag]			Boolean NOT NULL, 
	[ItemOnline]			Boolean NOT NULL, 
	[Selected]			Boolean NOT NULL, 
	[SupplierID]			Text (16), 
	[UseConsignmentPct]			Boolean NOT NULL, 
	[UseCommissionSchedule]			Boolean NOT NULL, 
	[CommissionSchedule]			Text (50), 
	[RetailPrice]			Currency, 
	[WholesalePrice]			Currency, 
	[Category2]			Text (50), 
	[Category3]			Text (50), 
	[Category4]			Text (50), 
	[Category5]			Text (50), 
	[UploadDate]			DateTime, 
	[UseDiscountPct]			Boolean NOT NULL, 
	[UID]			Double, 
	[AlternateID]			Text (16), 
	[BoothID]			Text (8), 
	[LabelQuantity]			Double, 
	[ItemIDValue]			Text (48), 
	[UseDiscountSchedule]			Boolean NOT NULL, 
	[DiscountSchedule]			Text (50), 
	[ImageFileName1]			Text (255), 
	[ImageFileName2]			Text (255), 
	[ImageFileName3]			Text (255), 
	[PurchaseDate]			DateTime, 
	[TransferQuantity]			Double, 
	[LastSoldDate]			DateTime, 
	[AgeRestriction]			Double, 
	[SoldQuantity]			Double, 
	[ShelfLife]			Double, 
	[Tare]			Double
);

CREATE TABLE [LayawayDealer]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[SalesMasterID]			Double, 
	[DealerID]			Text (8), 
	[LayawayPct]			Double
);

CREATE TABLE [LayawayDealer_DeletedTransactions]
 (
	[DID]			Double, 
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[SalesMasterID]			Double, 
	[DealerID]			Text (8), 
	[LayawayPct]			Double
);

CREATE TABLE [LayawayDetail]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[SalesMasterID]			Double, 
	[DueAmount]			Currency, 
	[DueDate]			DateTime, 
	[PaymentAmount]			Currency, 
	[PaymentDate]			DateTime, 
	[PaymentSalesMasterID]			Double
);

CREATE TABLE [LayawayDetail_DeletedTransactions]
 (
	[DID]			Double, 
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[SalesMasterID]			Double, 
	[DueAmount]			Currency, 
	[DueDate]			DateTime, 
	[PaymentAmount]			Currency, 
	[PaymentDate]			DateTime, 
	[PaymentSalesMasterID]			Double
);

CREATE TABLE [LayawayMaster_DeletedTransactions]
 (
	[DID]			Double, 
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[TimeDateStamp]			DateTime, 
	[CustomerID]			Double, 
	[Comments]			Memo/Hyperlink (255), 
	[History]			Memo/Hyperlink (255), 
	[Completed]			Boolean NOT NULL, 
	[SubTotal]			Double, 
	[Tax]			Double, 
	[Total]			Double, 
	[Cancelled]			Boolean NOT NULL, 
	[CancelledDate]			DateTime
);

CREATE TABLE [List]
 (
	[ListField]			Text (50), 
	[ListPosition]			Long Integer, 
	[ListLongDesc]			Text (255), 
	[ListNumeric]			Double, 
	[ListShortDesc]			Text (80), 
	[ListMemo]			Memo/Hyperlink (255), 
	[ListExtra]			Text (255), 
	[ListDate1]			DateTime, 
	[ListDate2]			DateTime, 
	[ID]			Long Integer, 
	[UpdatedCashier]			Text (20), 
	[UpdatedTDS]			DateTime
);

CREATE TABLE [LoyaltyDetail]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[StoreNumber]			Double, 
	[TID]			Double, 
	[DS]			DateTime, 
	[Description]			Text (255), 
	[Amount]			Currency, 
	[Points]			Double
);

CREATE TABLE [LoyaltyMaster]
 (
	[ID]			Double, 
	[LoyaltyID]			Text (16), 
	[BalanceAmount]			Currency
);

CREATE TABLE [OrderDetail]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[Supplier]			Text (100), 
	[DealerID]			Text (8), 
	[ItemID]			Text (16), 
	[Description]			Text (100), 
	[Price]			Currency, 
	[Quantity]			Double, 
	[PromiseDate]			DateTime, 
	[QuantityFilled]			Double
);

CREATE TABLE [OrderDetail_DeletedOrders]
 (
	[DID]			Double, 
	[ID]			Double, 
	[ParentID]			Double, 
	[Supplier]			Text (100), 
	[DealerID]			Text (8), 
	[ItemID]			Text (16), 
	[Description]			Text (100), 
	[Price]			Currency, 
	[Quantity]			Double, 
	[PromiseDate]			DateTime, 
	[QuantityFilled]			Double
);

CREATE TABLE [OrderMaster]
 (
	[ID]			Double, 
	[CustomerID]			Double, 
	[OrderDate]			DateTime, 
	[Status]			Text (50)
);

CREATE TABLE [OrderMaster_DeletedOrders]
 (
	[DID]			Double, 
	[ID]			Double, 
	[CustomerID]			Double, 
	[OrderDate]			DateTime, 
	[Status]			Text (50)
);

CREATE TABLE [ParkedSales]
 (
	[ID]			Long Integer, 
	[TimeDateStamp]			DateTime, 
	[Status]			Text (20), 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[TabNumber]			Long Integer, 
	[Data]			Memo/Hyperlink (255)
);

CREATE TABLE [RegisterList]
 (
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[MUID]			Text (23), 
	[Description]			Text (50), 
	[UseReceiptPrinter]			Boolean NOT NULL, 
	[ReceiptPrinter]			Text (255), 
	[ReceiptPrinterPort]			Text (255), 
	[UseReceiptPrinterLogo]			Boolean NOT NULL, 
	[UseCashDrawer]			Boolean NOT NULL, 
	[CashDrawer]			Text (255), 
	[CashDrawerPort]			Text (255), 
	[FullCloseOut]			Boolean NOT NULL, 
	[ReceiptPrinterCPL]			Long Integer, 
	[UseCheckout]			Boolean NOT NULL, 
	[UsePoleDisplay]			Boolean NOT NULL, 
	[PoleDisplay]			Text (50), 
	[PoleDisplayPort]			Text (50), 
	[CashDrawerDelay]			Double, 
	[ReceiptPrinterGap]			Long Integer, 
	[PoleDisplayIdleAction1]			Text (10), 
	[PoleDisplayIdleAction2]			Text (10), 
	[PoleDisplayIdleText1]			Text (100), 
	[PoleDisplayIdleText2]			Text (100), 
	[PoleDisplayIdleDirection1]			Text (15), 
	[PoleDisplayIdleDirection2]			Text (15), 
	[PoleDisplayIdleDelay1]			Double, 
	[PoleDisplayIdleDelay2]			Double, 
	[PoleDisplayUpdateTimer]			Double, 
	[ReportZoom]			Text (25), 
	[UseICCS]			Boolean NOT NULL, 
	[ICCS]			Text (30), 
	[ICCSExtra1]			Text (255), 
	[ICCSExtra2]			Text (255), 
	[ICCSExtra3]			Text (255), 
	[ICCSExtra4]			Text (255), 
	[ICCSExtra5]			Text (255), 
	[PoleDisplayURL]			Memo/Hyperlink (255), 
	[StartupBalance]			Boolean NOT NULL, 
	[StartupBalanceValue]			Currency, 
	[RegType]			Text (25), 
	[Passcode]			Text (8)
);

CREATE TABLE [Reports]
 (
	[ReportFileName]			Text (255), 
	[ReportDescription]			Text (255), 
	[ReportLabel1]			Memo/Hyperlink (255), 
	[ReportLabel2]			Memo/Hyperlink (255), 
	[ReportLabel3]			Memo/Hyperlink (255), 
	[ReportLabel4]			Memo/Hyperlink (255), 
	[ReportLabel5]			Memo/Hyperlink (255), 
	[ReportLabel6]			Memo/Hyperlink (255), 
	[ReportLabel7]			Memo/Hyperlink (255), 
	[ReportLabel8]			Memo/Hyperlink (255), 
	[ReportLabel9]			Memo/Hyperlink (255), 
	[ReportLabel10]			Memo/Hyperlink (255), 
	[ReportLabel11]			Memo/Hyperlink (255), 
	[ReportLabel12]			Memo/Hyperlink (255), 
	[ReportLabel13]			Memo/Hyperlink (255), 
	[ReportLabel14]			Memo/Hyperlink (255), 
	[ReportLabel15]			Memo/Hyperlink (255), 
	[ReportLabel16]			Memo/Hyperlink (255), 
	[ReportLabel17]			Memo/Hyperlink (255), 
	[ReportLabel18]			Memo/Hyperlink (255), 
	[ReportLabel19]			Memo/Hyperlink (255), 
	[ReportLabel20]			Memo/Hyperlink (255), 
	[ReportHelp]			Memo/Hyperlink (255), 
	[ReportSetSpecialFormula]			Memo/Hyperlink (255), 
	[LastRunDate]			DateTime, 
	[RunCount]			Long Integer, 
	[ReportUsesDates]			Boolean NOT NULL, 
	[UsesFirstDateOnly]			Boolean NOT NULL, 
	[UsesFirstDateOnlyUnlessAdmin]			Boolean NOT NULL, 
	[ReportExportable]			Boolean NOT NULL, 
	[AdminRequired]			Boolean NOT NULL, 
	[PrinterName]			Text (255), 
	[PrinterOrientation]			Long Integer, 
	[PaperBin]			Text (32), 
	[PaperType]			Text (64), 
	[HasSettlementVersion]			Boolean NOT NULL, 
	[SettlementReportFileName]			Text (255), 
	[Hidden]			Boolean NOT NULL, 
	[Favorite]			Long Integer, 
	[RetirementDate]			DateTime, 
	[RetirementNotes]			Memo/Hyperlink (255), 
	[IsAdHoc]			Boolean NOT NULL, 
	[IsLockedAdHoc]			Boolean NOT NULL, 
	[AdHocSQL]			Memo/Hyperlink (255), 
	[AdHocColData]			Text (255), 
	[IsLabel]			Boolean NOT NULL, 
	[IsSheetLabel]			Boolean NOT NULL, 
	[IsDailyOperationsReport]			Boolean NOT NULL, 
	[IsDealerReport]			Boolean NOT NULL, 
	[IsDealerInfoReport]			Boolean NOT NULL, 
	[IsCustomerReport]			Boolean NOT NULL, 
	[IsResellerReport]			Boolean NOT NULL, 
	[IsSalespersonReport]			Boolean NOT NULL, 
	[IsInventoryReport]			Boolean NOT NULL, 
	[IsStoreReport]			Boolean NOT NULL, 
	[IsTaxReport]			Boolean NOT NULL, 
	[IsItemLabel]			Boolean NOT NULL
);

CREATE TABLE [Reseller]
 (
	[ID]			Double, 
	[FirstName]			Text (50), 
	[LastName]			Text (50), 
	[Address1]			Text (50), 
	[Address2]			Text (50), 
	[City]			Text (50), 
	[State]			Text (4), 
	[ZIP]			Text (10), 
	[PrimaryPhone]			Text (20), 
	[AltPhone]			Text (20), 
	[MobilePhone]			Text (20), 
	[Email]			Text (80), 
	[Comments]			Memo/Hyperlink (255), 
	[Notes]			Memo/Hyperlink (255), 
	[ResellerNo]			Text (25), 
	[Company]			Text (50), 
	[MarketingOK]			Boolean NOT NULL, 
	[BusinessLicenseNo]			Text (25), 
	[Extra1]			Text (50), 
	[Extra2]			Text (50), 
	[Extra3]			Text (50), 
	[Extra4]			Text (50), 
	[Extra5]			Text (50), 
	[URL]			Text (255), 
	[MobileEmail]			Text (100), 
	[UseExpirationDate]			Boolean NOT NULL, 
	[ExpirationDate]			DateTime, 
	[DLN]			Text (20), 
	[RequireCashOnly]			Boolean NOT NULL, 
	[AllowChecks]			Boolean NOT NULL, 
	[AllowLayaways]			Boolean NOT NULL, 
	[ShippingUseContact]			Boolean NOT NULL, 
	[ShippingFirstName]			Text (50), 
	[ShippingLastName]			Text (50), 
	[ShippingAddress1]			Text (50), 
	[ShippingAddress2]			Text (50), 
	[ShippingCity]			Text (50), 
	[ShippingState]			Text (20), 
	[ShippingZIP]			Text (10), 
	[ShippingPhone]			Text (20), 
	[Country]			Text (50), 
	[ShippingCountry]			Text (50), 
	[EditDate]			DateTime, 
	[UploadDate]			DateTime, 
	[DOB]			DateTime, 
	[LoyaltyID]			Text (16), 
	[LoyaltyPlan]			Text (50)
);

CREATE TABLE [SalesDetail_DeletedTransactions]
 (
	[DID]			Double, 
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[DealerID]			Text (8), 
	[DealerPct]			Double, 
	[ItemDescription]			Text (255), 
	[ConsignmentPct]			Double, 
	[DiscountPct]			Double, 
	[FullPrice]			Currency, 
	[Price]			Currency, 
	[AmountPosted]			Currency, 
	[LayawayPayment]			Boolean NOT NULL, 
	[Quantity]			Double, 
	[ItemPrice]			Currency, 
	[EditTimeDateStamp]			DateTime, 
	[EditHistory]			Memo/Hyperlink (255), 
	[ItemID]			Text (16), 
	[InventoryItem]			Boolean NOT NULL, 
	[BoothID]			Text (8), 
	[SettlementID]			Double, 
	[Taxed]			Boolean NOT NULL, 
	[TaxID]			Double, 
	[TaxCategory]			Text (100), 
	[TaxRate]			Double, 
	[OrderMasterID]			Double, 
	[OrderDetailID]			Double, 
	[DeletedSettlementID]			Double, 
	[Cost]			Currency, 
	[CashierID]			Text (20), 
	[CashierCommissionPct]			Double, 
	[Void]			Boolean NOT NULL, 
	[VoidTID]			Double, 
	[RentAppliedDate]			DateTime, 
	[HoldConsignmentPct]			Double, 
	[HoldDealerPct]			Double, 
	[UseConsignmentPct]			Boolean NOT NULL
);

CREATE TABLE [SalesDetail_PermanentlyDeleted]
 (
	[ID]			Double, 
	[TimeDateStamp]			DateTime, 
	[Cashier]			Text (20), 
	[Comments]			Memo/Hyperlink (255), 
	[TID]			Double
);

CREATE TABLE [SalesMaster]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[TimeDateStamp]			DateTime, 
	[Cashier]			Text (20), 
	[PaymentType]			Text (20) NOT NULL, 
	[CheckNumber]			Text (20), 
	[DLN]			Text (20), 
	[CCAuthorizationNumber]			Text (50), 
	[CCTransactionID]			Text (255), 
	[Layaway]			Boolean NOT NULL, 
	[Total]			Currency, 
	[TotalDue]			Currency, 
	[Taxable]			Boolean NOT NULL, 
	[Tax]			Currency, 
	[Tendered]			Currency, 
	[Change]			Currency, 
	[TaxRate]			Double, 
	[Void]			Boolean NOT NULL, 
	[VoidReason]			Memo/Hyperlink (255), 
	[CollectionRequired]			Boolean NOT NULL, 
	[EditTimeDateStamp]			DateTime, 
	[SubTotal]			Currency, 
	[EditHistory]			Memo/Hyperlink (255), 
	[LayawayTaxRule]			Long Integer, 
	[TaxDue]			Currency, 
	[CashAmount]			Currency, 
	[CheckAmount]			Currency, 
	[CreditAmount]			Currency, 
	[GiftCertificateAmount]			Currency, 
	[GiftCertificateNumber]			Double, 
	[CheckFee]			Currency, 
	[CreditCardFee]			Currency, 
	[CustomerID]			Double, 
	[DebitFee]			Currency, 
	[DebitAmount]			Currency, 
	[DCAuthorizationNumber]			Text (50), 
	[DCTransactionID]			Text (20), 
	[ResellerID]			Double, 
	[PersonID]			Double, 
	[PersonType]			Text (50), 
	[CostPriceType]			Text (20), 
	[NoSaleAmount]			Currency, 
	[InventoryAction]			Text (20), 
	[StateTaxRate]			Double, 
	[CountyTaxRate]			Double, 
	[CityTaxRate]			Double, 
	[AlternateInvoiceNo]			Text (50), 
	[AccountAmount]			Currency, 
	[AccountDealerID]			Text (8), 
	[ChargeAmount]			Currency, 
	[ChargeFee]			Currency, 
	[CHAuthorizationNumber]			Text (50), 
	[CHTransactionID]			Text (20), 
	[GiftCardAmount]			Currency, 
	[GiftCardFee]			Currency, 
	[GiftCardAuthorizationNumber]			Text (50), 
	[HasNotes]			Boolean NOT NULL, 
	[Notes]			Memo/Hyperlink (255), 
	[NotesLocked]			Boolean NOT NULL, 
	[QRBarcodeData]			Text (255), 
	[GiftCardTransactionID]			Text (20), 
	[CCVoidTransactionID]			Text (255), 
	[DCVoidTransactionID]			Text (20), 
	[CHVoidTransactionID]			Text (20), 
	[GiftCardVoidTransactionID]			Text (20), 
	[CCVoidAuthorizationNumber]			Text (20), 
	[DCVoidAuthorizationNumber]			Text (20), 
	[CHVoidAuthorizationNumber]			Text (20), 
	[GiftCardVoidAuthorizationNumber]			Text (20), 
	[FlexPaymentType]			Text (20)
);

CREATE TABLE [SalesMaster_DeletedTransactions]
 (
	[DID]			Double, 
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[TimeDateStamp]			DateTime, 
	[Cashier]			Text (20), 
	[PaymentType]			Text (20), 
	[CheckNumber]			Text (20), 
	[DLN]			Text (20), 
	[CCAuthorizationNumber]			Text (50), 
	[CCTransactionID]			Text (255), 
	[Layaway]			Boolean NOT NULL, 
	[Total]			Currency, 
	[TotalDue]			Currency, 
	[Taxable]			Boolean NOT NULL, 
	[Tax]			Currency, 
	[Tendered]			Currency, 
	[Change]			Currency, 
	[TaxRate]			Double, 
	[Void]			Boolean NOT NULL, 
	[VoidReason]			Memo/Hyperlink (255), 
	[CollectionRequired]			Boolean NOT NULL, 
	[EditTimeDateStamp]			DateTime, 
	[SubTotal]			Currency, 
	[EditHistory]			Memo/Hyperlink (255), 
	[LayawayTaxRule]			Long Integer, 
	[TaxDue]			Currency, 
	[CashAmount]			Currency, 
	[CheckAmount]			Currency, 
	[CreditAmount]			Currency, 
	[GiftCertificateAmount]			Currency, 
	[GiftCertificateNumber]			Double, 
	[CheckFee]			Currency, 
	[CreditCardFee]			Currency, 
	[CustomerID]			Double, 
	[DebitFee]			Currency, 
	[DebitAmount]			Currency, 
	[DCAuthorizationNumber]			Text (50), 
	[DCTransactionID]			Text (20), 
	[ResellerID]			Double, 
	[PersonID]			Double, 
	[PersonType]			Text (50), 
	[CostPriceType]			Text (20), 
	[NoSaleAmount]			Currency, 
	[InventoryAction]			Text (20), 
	[StateTaxRate]			Double, 
	[CountyTaxRate]			Double, 
	[CityTaxRate]			Double, 
	[AlternateInvoiceNo]			Text (50), 
	[AccountAmount]			Currency, 
	[AccountDealerID]			Text (8), 
	[ChargeAmount]			Currency, 
	[ChargeFee]			Currency, 
	[CHAuthorizationNumber]			Text (50), 
	[CHTransactionID]			Text (20), 
	[GiftCardAmount]			Currency, 
	[GiftCardFee]			Currency, 
	[GiftCardAuthorizationNumber]			Text (50), 
	[HasNotes]			Boolean NOT NULL, 
	[Notes]			Memo/Hyperlink (255), 
	[NotesLocked]			Boolean NOT NULL, 
	[QRBarcodeData]			Text (255), 
	[GiftCardTransactionID]			Text (20), 
	[CCVoidTransactionID]			Text (255), 
	[DCVoidTransactionID]			Text (20), 
	[CHVoidTransactionID]			Text (20), 
	[GiftCardVoidTransactionID]			Text (20), 
	[CCVoidAuthorizationNumber]			Text (20), 
	[DCVoidAuthorizationNumber]			Text (20), 
	[CHVoidAuthorizationNumber]			Text (20), 
	[GiftCardVoidAuthorizationNumber]			Text (20), 
	[FlexPaymentType]			Text (20)
);

CREATE TABLE [Sequence]
 (
	[TableName]			Text (50), 
	[FieldName]			Text (50), 
	[Increment]			Long Integer, 
	[CurrentValue]			Double
);

CREATE TABLE [SettlementMaster]
 (
	[ID]			Double, 
	[Description]			Text (255), 
	[Status]			Text (20), 
	[AuditDatabase]			Text (255), 
	[PayoutDate]			DateTime, 
	[PayoutStartDate]			DateTime, 
	[PayoutEndDate]			DateTime, 
	[PayoutFrequency]			Text (80), 
	[SemiMonthly]			Long Integer, 
	[RentDueDate]			DateTime, 
	[RentStartDate]			DateTime, 
	[RentEndDate]			DateTime, 
	[RentFrequency]			Text (50), 
	[RentDue]			Text (50), 
	[RentMethod]			Text (50), 
	[FeeDueDate]			DateTime, 
	[FeeStartDate]			DateTime, 
	[FeeEndDate]			DateTime, 
	[FeeFrequency]			Text (50), 
	[FeeDue]			Text (50), 
	[FeeMethod]			Text (50), 
	[BackupTimeDateStamp]			DateTime, 
	[RentDueFlag]			Boolean NOT NULL, 
	[RentPaymentsFlag]			Boolean NOT NULL, 
	[LastEditTDS]			DateTime, 
	[LastFTPTDS]			DateTime, 
	[RentDueDay]			Long Integer, 
	[FeeDueDay]			Long Integer, 
	[PrintDate]			DateTime
);

CREATE TABLE [States]
 (
	[ID]			Text (20), 
	[Name]			Text (50), 
	[ResellerVerificationURL]			Text (255), 
	[ResellerVerificationPOSTDATA]			Text (255), 
	[StateTaxIDNo]			Text (20), 
	[Country]			Text (50)
);

CREATE TABLE [StoreList]
 (
	[StoreNumber]			Long Integer, 
	[StoreName]			Text (50), 
	[StoreAddr1]			Text (50), 
	[StoreAddr2]			Text (50), 
	[StoreCity]			Text (50), 
	[StoreState]			Text (4), 
	[StoreZIP]			Text (10), 
	[StorePhone]			Text (14)
);

CREATE TABLE [Tax]
 (
	[ID]			Double, 
	[Category]			Text (50), 
	[Department]			Text (100), 
	[Rate]			Double, 
	[StartDate]			DateTime, 
	[EndDate]			DateTime
);

CREATE TABLE [TransactionTotals]
 (
	[DS]			DateTime, 
	[Description]			Text (100), 
	[Total]			Currency, 
	[Tax]			Currency, 
	[CashTotal]			Currency, 
	[CheckTotal]			Currency, 
	[CreditTotal]			Currency, 
	[DebitTotal]			Currency, 
	[ChargeTotal]			Currency, 
	[GiftCardTotal]			Currency, 
	[GiftCertificateTotal]			Currency, 
	[AccountTotal]			Currency, 
	[NoSaleTotal]			Currency, 
	[QuantityTotal]			Double, 
	[DiscountTotal]			Currency, 
	[CommissionTotal]			Currency, 
	[GiftCertificateSoldTotal]			Currency, 
	[CouponTotal]			Currency
);

CREATE TABLE [WantList]
 (
	[ID]			Double, 
	[CustomerID]			Double, 
	[Item]			Text (80), 
	[DateAdded]			DateTime, 
	[ResellerID]			Double, 
	[EditDate]			DateTime, 
	[UploadDate]			DateTime
);

CREATE TABLE [DealerRent]
 (
	[ID]			Long Integer, 
	[DealerID]			Text (8), 
	[Rent]			Currency, 
	[StartDate]			DateTime, 
	[EndDate]			DateTime, 
	[Comments]			Text (100)
);

CREATE TABLE [History]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[TDS]			DateTime, 
	[TableName]			Text (50), 
	[IDField]			Text (50), 
	[IDValue]			Text (50), 
	[TextValue1]			Text (255), 
	[NumericValue1]			Double, 
	[DateValue1]			DateTime, 
	[TextValue2]			Text (255), 
	[NumericValue2]			Double, 
	[DateValue2]			DateTime, 
	[TextValue3]			Text (255), 
	[NumericValue3]			Double, 
	[DateValue3]			Text (50), 
	[Comments]			Memo/Hyperlink (255)
);

CREATE TABLE [LayawayMaster]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[TimeDateStamp]			DateTime, 
	[CustomerID]			Double, 
	[Comments]			Memo/Hyperlink (255), 
	[History]			Memo/Hyperlink (255), 
	[Completed]			Boolean NOT NULL, 
	[SubTotal]			Double, 
	[Tax]			Double, 
	[Total]			Double, 
	[Cancelled]			Boolean NOT NULL, 
	[CancelledDate]			DateTime
);

CREATE TABLE [SalesDetail]
 (
	[ID]			Double, 
	[StoreNumber]			Long Integer, 
	[RegisterNumber]			Long Integer, 
	[ParentID]			Double, 
	[DealerID]			Text (8), 
	[DealerPct]			Double, 
	[ItemID]			Text (16), 
	[ItemDescription]			Text (255), 
	[ConsignmentPct]			Double, 
	[DiscountPct]			Double, 
	[FullPrice]			Currency, 
	[Price]			Currency, 
	[AmountPosted]			Currency, 
	[LayawayPayment]			Boolean NOT NULL, 
	[Quantity]			Double, 
	[ItemPrice]			Currency, 
	[EditTimeDateStamp]			DateTime, 
	[EditHistory]			Memo/Hyperlink (255), 
	[InventoryItem]			Boolean NOT NULL, 
	[BoothID]			Text (8), 
	[SettlementID]			Double, 
	[Taxed]			Boolean NOT NULL, 
	[TaxID]			Double, 
	[TaxCategory]			Text (100), 
	[TaxRate]			Double, 
	[OrderMasterID]			Double, 
	[OrderDetailID]			Double, 
	[Cost]			Currency, 
	[CashierID]			Text (20), 
	[CashierCommissionPct]			Double, 
	[Void]			Boolean NOT NULL, 
	[VoidTID]			Double, 
	[RentAppliedDate]			DateTime, 
	[HoldConsignmentPct]			Double, 
	[HoldDealerPct]			Double, 
	[UseConsignmentPct]			Boolean NOT NULL
);

CREATE TABLE [SettlementDetail]
 (
	[ID]			Double, 
	[ParentID]			Double, 
	[DealerID]			Text (8), 
	[DealerName]			Text (100), 
	[SalesTotal]			Currency, 
	[RentTotal]			Currency, 
	[FeeTotal]			Currency, 
	[CreditTotal]			Currency, 
	[DebitTotal]			Currency, 
	[PriorBalance]			Currency, 
	[CurrentBalance]			Currency, 
	[ActualPaid]			Currency, 
	[PaymentType]			Text (50), 
	[PaymentTypeID]			Text (20), 
	[PaymentTypeMemo]			Text (255), 
	[Selected]			Boolean NOT NULL
);


